In [2]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df=pd.read_csv("House_Pricing.csv")

Saving House_Pricing.csv to House_Pricing (1).csv

In [12]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [11]:
#remove duplicate rows
duplicate_rows=df.duplicated().sum()
print(f"Number of duplicate rows:{duplicate_rows}")
#drop duplicate rows
df=df.drop_duplicates()

Number of duplicate rows:0

In [9]:
#Remove duplicate columns
df = df.loc[:, ~df.T.duplicated()]
#Confirming duplicates were removed
print("Updated shape of dataset:" , df.shape)

Updated shape of dataset: (21613, 21)

In [13]:
#Handling missing values
# Show the number of missing values in each column
df.isnull().sum().sort_values(ascending=False)

No of Times Visited                          19489
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Bathrooms                                  4
Sale Price                                       4
Area of the House from Basement (in Sqft)        3
Latitude                                         1
Living Area after Renovation (in Sqft)           1
Longitude                                        1
Zipcode                                          1
No of Bedrooms                                   0
ID                                               0
Date House was Sold                              0
Overall Grade                                    0
Condition of the House                           0
No of Floors                                     0
Waterfront View                                  0
Renovated Year                                   0
Age of House (in Years)                          0
Basement Area (in Sqft)                          0
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [14]:
#Handle missing values:
from sklearn.impute import SimpleImputer

# Separate numerical and categorical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns

# Create imputers
mean_imputer = SimpleImputer(strategy='mean')          # For numerical features
mode_imputer = SimpleImputer(strategy='most_frequent') # For categorical features

# Apply mean imputation to numerical columns
df[numerical_cols] = mean_imputer.fit_transform(df[numerical_cols])

# Apply mode imputation to categorical columns (if any)
if len(categorical_cols) > 0:
    df[categorical_cols] = mode_imputer.fit_transform(df[categorical_cols])

# Confirm no missing values remain
df.isnull().sum().sum()

np.int64(0)

In [15]:
#documentation of dataset
missing_values = df.isnull().sum()
missing_columns = missing_values[missing_values > 0]
print(missing_columns)

Series([], dtype: int64)

In [17]:
#scaling numerical variables
from sklearn.preprocessing import StandardScaler

# Identify all numerical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Remove the target variable (correct name)
numerical_cols.remove('Sale Price')

# Initialize the scaler
scaler = StandardScaler()

# Scale the numerical columns
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

# (Optional) Check the result
print(df[numerical_cols].describe())

                 ID  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
count  2.161300e+04    2.161300e+04     2.161300e+04         2.161300e+04
mean   1.144075e-16    2.367051e-16    -5.891327e-16        -1.183526e-16
std    1.000023e+00    1.000023e+00     1.000023e+00         1.000023e+00
min   -1.591970e+00   -3.624404e+00    -2.746230e+00        -1.949233e+00
25%   -8.542511e-01   -3.987371e-01    -4.736480e-01        -7.077746e-01
50%   -2.347893e-01   -3.987371e-01     1.756611e-01        -1.850554e-01
75%    9.485833e-01    6.764851e-01     5.003157e-01         5.119035e-01
max    1.849366e+00    3.185793e+01     7.642716e+00         1.247999e+01

       Lot Area (in Sqft)  No of Floors  Overall Grade  \
count        2.161300e+04  2.161300e+04   2.161300e+04
mean         6.312136e-17 -3.156068e-17   2.367051e-16
std          1.000023e+00  1.000023e+00   1.000023e+00
min         -3.522024e-01 -9.154270e-01  -5.991845e+00
25%         -2.430729e-01 -9.154270e-01  -5.640127e-01
50%         -1.807821e-01  1.053939e-02  -5.640127e-01
75%         -1.063954e-01  9.365058e-01   3.406260e-01
max          3.950515e+01  3.714405e+00   2.149903e+00

       Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  \
count                               2.161300e+04             2.161300e+04
mean                               -2.524855e-16             6.838148e-17
std                                 1.000023e+00             1.000023e+00
min                                -1.809800e+00            -6.586810e-01
25%                                -7.227200e-01            -6.586810e-01
50%                                -2.758093e-01            -6.586810e-01
75%                                 5.093040e-01             6.066704e-01
max                                 9.205944e+00             1.023238e+01

       Age of House (in Years)  Renovated Year       Zipcode      Latitude  \
count             21613.000000    2.161300e+04  2.161300e+04  2.161300e+04
mean                  0.000000    1.315028e-18 -3.311439e-14  2.325381e-14
std                   1.000023    1.000023e+00  1.000023e+00  1.000023e+00
min                  -1.497813   -2.101284e-01 -1.438010e+00 -2.916799e+00
25%                  -0.885000   -2.101284e-01 -8.399119e-01 -6.426710e-01
50%                  -0.136006   -2.101284e-01 -2.418141e-01  8.481895e-02
75%                   0.681079   -2.101284e-01  7.487855e-01  8.512816e-01
max                   2.417383    4.806428e+00  2.262721e+00  1.570111e+00

          Longitude  Living Area after Renovation (in Sqft)  \
count  2.161300e+04                            2.161300e+04
mean  -8.456685e-14                            3.839883e-16
std    1.000023e+00                            1.000023e+00
min   -2.166605e+00                           -2.316315e+00
25%   -8.102955e-01                           -7.244803e-01
50%   -1.143878e-01                           -2.138091e-01
75%    6.312277e-01                            5.449023e-01
max    6.383118e+00                            6.162285e+00

       Lot Area after Renovation (in Sqft)
count                         2.161300e+04
mean                         -2.893063e-17
std                           1.000023e+00
min                          -4.438052e-01
25%                          -2.808593e-01
50%                          -1.885636e-01
75%                          -9.835556e-02
max                           3.144029e+01

In [21]:
#Scale these features using techniques like Min-Max scaling or Standard scaling.
# Identify numerical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Remove target variable (ensure column name matches exactly)
numerical_cols.remove('Sale Price')  # Update if your target column name is different

from sklearn.preprocessing import StandardScaler

# Initialize scaler
standard_scaler = StandardScaler()

# Apply to numerical columns
df[numerical_cols] = standard_scaler.fit_transform(df[numerical_cols])

from sklearn.preprocessing import MinMaxScaler

# Initialize scaler
minmax_scaler = MinMaxScaler()

# Apply to numerical columns
df[numerical_cols] = minmax_scaler.fit_transform(df[numerical_cols])

# Check summary statistics
print(df[numerical_cols].describe())

                 ID  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
count  21613.000000    21613.000000     21613.000000         21613.000000
mean       0.462602        0.102147         0.264342             0.135089
std        0.290592        0.028184         0.096258             0.069305
min        0.000000        0.000000         0.000000             0.000000
25%        0.214370        0.090909         0.218750             0.086038
50%        0.394376        0.090909         0.281250             0.122264
75%        0.738246        0.121212         0.312500             0.170566
max        1.000000        1.000000         1.000000             1.000000

       Lot Area (in Sqft)  No of Floors  Overall Grade  \
count        21613.000000  21613.000000   21613.000000
mean             0.008837      0.197724       0.735941
std              0.025090      0.215996       0.122827
min              0.000000      0.000000       0.000000
25%              0.002738      0.000000       0.666667
50%              0.004301      0.200000       0.666667
75%              0.006167      0.400000       0.777778
max              1.000000      1.000000       1.000000

       Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  \
count                               21613.000000             21613.000000
mean                                    0.164292                 0.060479
std                                     0.090781                 0.091821
min                                     0.000000                 0.000000
25%                                     0.098684                 0.000000
50%                                     0.139254                 0.000000
75%                                     0.210526                 0.116183
max                                     1.000000                 1.000000

       Age of House (in Years)  Renovated Year       Zipcode      Latitude  \
count             21613.000000    21613.000000  21613.000000  21613.000000
mean                  0.382564        0.041887      0.388575      0.650069
std                   0.255421        0.199345      0.270223      0.222876
min                   0.000000        0.000000      0.000000      0.000000
25%                   0.156522        0.000000      0.161616      0.506836
50%                   0.347826        0.000000      0.323232      0.668972
75%                   0.556522        0.000000      0.590909      0.839794
max                   1.000000        1.000000      1.000000      1.000000

          Longitude  Living Area after Renovation (in Sqft)  \
count  21613.000000                            21613.000000
mean       0.253412                                0.273195
std        0.116966                                0.117947
min        0.000000                                0.000000
25%        0.158638                                0.187747
50%        0.240033                                0.247978
75%        0.327243                                0.337463
max        1.000000                                1.000000

       Lot Area after Renovation (in Sqft)
count                         21613.000000
mean                              0.013919
std                               0.031364
min                               0.000000
25%                               0.005111
50%                               0.008005
75%                               0.010835
max                               1.000000

In [22]:
#Encoding Categorical Variables
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

# Preview the columns
print("Categorical columns:", categorical_cols)

Categorical columns: ['Date House was Sold', 'Waterfront View', 'No of Times Visited', 'Condition of the House']

In [26]:
#train-test split
from sklearn.model_selection import train_test_split
# Features (all columns except 'Sale Price')
X = df.drop('Sale Price', axis=1)
# Target variable
y = df['Sale Price']
# Split the dataset into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"Training Features Shape: {X_train.shape}")
print(f"Testing Features Shape: {X_test.shape}")
print(f"Training Labels Shape: {y_train.shape}")
print(f"Testing Labels Shape: {y_test.shape}")

Training Features Shape: (17290, 20)
Testing Features Shape: (4323, 20)
Training Labels Shape: (17290,)
Testing Labels Shape: (4323,)